[workspace]
resolver = "3"
members = ["crates/bevy_deterministic", "crates/fx"]

[workspace.dependencies]
fx = { path = "crates/fx" }

bevy = "0.17.3"
fixed = { version = "1.29.0", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
strum = "0.27.2"
strum_macros = "0.27.2"
rustc-hash = "2.1.1"
indexmap = "2.12.1"
