[package]
name = "bevy_deterministic"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"
fixed = { version = "1.29.0", features = ["serde"] }
bevy-inspector-egui = "0.35.0"
serde = { version = "1.0.228", features = ["derive"] }
