[package]
name = "render"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true, default-features = true }
whitelace_core.workspace = true
whitelace_physics.workspace = true
whitelace_transform.workspace = true
