[package]
name = "whitelace_transform"
version = "0.1.0"
edition = "2024"

[dependencies]
whitelace_math.workspace = true
whitelace_core.workspace = true
whitelace_sync.workspace = true

[dependencies.bevy]
workspace = true
