[package]
name = "sync"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_deterministic.workspace = true
bridge.workspace = true
impl-trait-for-tuples.workspace = true

[dependencies.bevy]
workspace = true
default-features = true
