[package]
name = "bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
fixed_math.workspace = true
bevy_deterministic.workspace = true
indexmap.workspace = true
rustc-hash.workspace = true

[dependencies.bevy]
workspace = true
default-features = true
