[package]
name = "whitelace_time"
version = "0.1.0"
edition = "2024"

[dependencies]
fixed_math.workspace = true
whitelace_core.workspace = true
whitelace_sync.workspace = true

[dependencies.bevy]
workspace = true
features = []
